#!/bin/sh
# postinst script for nokia-n900-configs
#
# see: dh_installdeb(1)

set -e

MAP_FILE=/usr/share/keymaps/arm/qwerty/nokia-n900.map
KBD_FILE=/etc/default/keyboard

case "$1" in
    configure)
        if [ -f $KBD_FILE ] && ! grep -q '^#\?KMAP=' $KBD_FILE ; then
            echo "KMAP=\"$MAP_FILE\"" >> $KBD_FILE
            invoke-rc.d console-setup.sh reload
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
